name: Deploy ASP.NET Core 8.0 to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    # Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # Publish the project
    - name: Publish project
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    # Deploy to Azure Web App
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YourWebAppName' # Replace with your Azure Web App name
        slot-name: 'production' # Optional: If you have a deployment slot, you can specify it here
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Set up this secret in your repository settings
        package: ${{env.DOTNET_ROOT}}/myapp

```